version: '3.9'
name: 5400-project

services:

    db:
        build: db
        image: project2/sentiment-analysis-db
        ports:
            - '5432:5432'

    client_gui:
        build: 
            context: client_gui/ClientGUI/
            dockerfile: Dockerfile
        image: project2/client_gui
        ports:
            - '32768:80'

    sentiment_analysis:
        build: sentiment_analysis
        image: project2/sentiment-analysis-sentiment_analysis
        ports:
            - '8000:8000'

   